std = 'lua51'
codes = true
max_line_length = false

exclude_files = {
    '**/.libraries/',
    '**/.history/',
    '**/Libs/',
    '**/libs/',
}

globals = {
    'BINDING_HEADER_DISENCHANTUM',
    'SLASH_DISENCHANTUM1',
    'SLASH_DISENCHANTUM2',
    'SlashCmdList',
    'StaticPopupDialogs',
}

read_globals = {
    'C_AddOns',
    'C_Container',
    'C_Cursor',
    'C_Item',
    'C_Spell',
    'C_SpellBook',
    'C_Timer',
    'C_TooltipInfo',
    'C_TradeSkillUI',
    'ClearCursor',
    'Constants',
    'CreateAtlasMarkup',
    'CreateColor',
    'CreateFrame',
    'Enum',
    'EventRegistry',
    'EXPANSION_FILTER_TEXT',
    'FILTERS',
    'GameFontHighlight',
    'GameFontHighlightSmall',
    'GameFontNormalSmall',
    'GameFontNormalLarge',
    'GameFontDisable',
    'GameTooltip',
    'GetClientDisplayExpansionLevel',
    'GetCursorPosition',
    'GetExpansionLevel',
    'GetMaximumExpansionLevel',
    'GetNumExpansions',
    'GetScreenHeight',
    'GetScreenWidth',
    'GetTime',
    'GetLocale',
    'HUD_EDIT_MODE_BAGS_LABEL',
    'InCombatLockdown',
    'IsMouseButtonDown',
    'ITEM_QUALITY2_DESC',
    'ITEM_QUALITY3_DESC',
    'ITEM_QUALITY4_DESC',
    'ITEM_SOULBOUND',
    'ItemLocation',
    'LibStub',
    'LootSlot',
    'GetLootSlotInfo',
    'GetLootSlotLink',
    'GetLootSlotType',
    'GetNumLootItems',
    'MINIMAP_LABEL',
    'NONE',
    'NumberFontNormal',
    'OTHER',
    'ProfessionsFrame',
    'ProfessionsUtil',
    'QUALITY',
    'RARITY',
    'RESET',
    'StaticPopup_Show',
    'StaticPopup_ShowCustomGenericConfirmation',
    'STAT_AVERAGE_ITEM_LEVEL',
    'strcmputf8i',
    'strupper',
    'TextureKitConstants',
    'UIParent',
    'UISpecialFrames',
    'UnitCastingInfo',
    'wipe',
    'YES',
    'CANCEL',
}

files['Locales/*.lua'] = {
    ignore = {
        '211',
    },
}
